### ISSUE TITLE
dedicated servers?

### ISSUE THREAD

**Issue by morrissimo** [Hatchibombotar/graves-addon#2]
Does this addon work on dedicated bedrock servers? Trying to get it running on bedrock server v1.20.62.02

**Comment by Hatchibombotar** [comment]
There's no reason it shouldn't work. Are any errors popping up?

**Comment by morrissimo** [comment]
> There's no reason it shouldn't work. Are any errors popping up?

Nothing that I can see, either on startup or when a player dies in-game.

In fact, after restarting the server with the graves behavior and resource packs in place, the server updated its `valid_known_packs.json` with entries for the graves behavior and resource pack entries - which _smells_ like everything is wired up correctly 🤷

**Comment by morrissimo** [comment]
doh, I figured it out: I had the `world_behavior_packs.json` and `world_resource_packs.json` files in the wrong dir. It works now 🎉 Thanks!
